name: CI Pipeline (Simplified)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #################################################
      # 1) Check out the repository
      #################################################
      - name: Checkout
        uses: actions/checkout@v3

      #################################################
      # 2) Set up Java
      #################################################
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      #################################################
      # 3) Install JFrog CLI
      #################################################
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | bash
          chmod +x jfrog
          mv jfrog /usr/local/bin/

      #################################################
      # 4) Configure JFrog CLI
      #################################################
      - name: Configure JFrog CLI
        run: |
          jfrog config add my-artifactory \
            --artifactory-url=https://trialt0zppb.jfrog.io/artifactory \
            --user="${{ secrets.ARTIFACTORY_USERNAME }}" \
            --password="${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}" \
            --interactive=false

      #################################################
      # 5) (Optional) Modify Maven Settings to Use Artifactory
      #
      # This is optional if your project's pom.xml references
      # standard Maven Central. If you do want all dependencies
      # to come from Artifactory, you can still do:
      #
      #   jfrog rt mvnc --server-id-resolve=my-artifactory ...
      #
      # but it may not be strictly necessary if the goal
      # is simply to upload the final artifact.
      #################################################

      #################################################
      # 6) Clear the local Maven cache
      #################################################
      - name: Clear local Maven cache
        run: rm -rf ~/.m2/repository

      #################################################
      # 7) Build with standard Maven (no build-info extraction)
      #################################################
      - name: Maven Build
        run: mvn clean package -DskipTests

      #################################################
      # 8) Upload the built artifact with JFrog CLI
      #
      # target/*.jar -> maven-libs-release-local (or whichever repo you prefer)
      #################################################
      - name: Upload Maven Artifact to Artifactory
        run: |
          jfrog rt upload \
            "target/*.jar" \
            "maven-libs-release-local/spring-petclinic/" \
            --flat=false \
            --build-name="spring-petclinic" \
            --build-number="${{ github.run_id }}"

      #################################################
      # 9) Build Docker image with local Docker
      #################################################
      - name: Build Docker Image
        run: |
          docker build -t trialt0zppb.jfrog.io/onboarding-docker-local/spring-petclinic:${{ github.run_id }} .

      #################################################
      # 10) Push Docker image using JFrog CLI
      #################################################
      - name: Push Docker Image to Artifactory
        run: |
          jfrog rt docker-push \
            trialt0zppb.jfrog.io/onboarding-docker-local/spring-petclinic:${{ github.run_id }} \
            onboarding-docker-local \
            --build-name="spring-petclinic" \
            --build-number="${{ github.run_id }}"

      #################################################
      # 11) Collect & Publish Build Info
      #
      # This won't include the dependency graph from
      # "jfrog rt mvn", but you'll still get:
      #  - The JAR(s) you uploaded
      #  - Docker image(s)
      #  - Environment info
      #################################################
      - name: Publish Build Info
        run: |
          jfrog rt build-publish \
            "spring-petclinic" \
            "${{ github.run_id }}"
